main: xyz.prorickey.classicdupe.ClassicDupe
name: ClassicDupe
version: 1.0.0-beta
api-version: 1.19
author: Prorickey
depend:
  - LuckPerms
commands:
  dupe:
    description: To dupe items. Can dupe up to 6 times
  filter:
    description: To add, remove or list the filter
    permission: admin.filter
  random:
    description: To toggle random items
  spawn:
    description: Teleports you to spawn
  setspawn:
    description: Sets the spawn to the players location
    permission: admin.setspawn
  gamemode:
    aliases:
      - gm
      - gmode
    permission: admin.gamemode
    description: To change the player's own gamemode or others
    usage: /<command> <gamemode> <player>
  gmc:
    aliases:
      - gamemodecreative
    permission: admin.gamemode.creative
    description: To change the player's own gamemode or others to creative mode
    usage: /<command> <player>
  gms:
    aliases:
      - gamemodesurvival
    permission: admin.gamemode.survival
    description: To change the player's own gamemode or others to survival mode
    usage: /<command> <player>
  gmsp:
    aliases:
      - gamemodespectator
    permission: admin.gamemode.spectator
    description: To change the player's own gamemode or others to spectator mode
    usage: /<command> <player>
  gma:
    aliases:
      - gamemodeadventure
    permission: admin.gamemode.adventure
    description: To change the player's own gamemode or others to adventure mode
    usage: /<command> <player>
  schedulerestart:
    permission: admin.restart
    description: To restart the server or cancel a server restart
  mutechat:
    permission: mod.mutechat
    description: To mute or unmute the chat
  chatcolor:
    permission: perks.colorchat
    description: To change the color of your chat
  gradient:
    permission: perks.gradient
    description: To add a little zest to your messages
  staffchat:
    permission: mod.staffchat
    description: To enable or disable staff chat 
    aliases: 
      - sc 
      - schat
  repair:
    permission: perk.repair
    description: To repair the item in a players main hand
  clearchat:
    permission: mod.clearchat
    description: To clear the chat
    aliases:
      - cc
  pm:
    description: To send a private message
  pmr:
    description: To reply to a private message
  head:
    description: To get the head of a player
    permission: admin.head
  spec:
    description: To switch between spectator and survival mode as a mod
    permission: mod.spec
  broadcast:
    description: To broadcast a message to the server
    permission: mod.broadcast
  sudo:
    description: To sudo another player
    permission: admin.sudo
  pv:
    description: To open and access different private vaults
    permission: perk.pv
  pvadd:
    description: To add a player vault to a player
    permission: admin.pvadd
  invsee:
    description: TO open and see a player's inventory
    permission: admin.invsee