main: xyz.prorickey.classicdupe.ClassicDupe
name: ClassicDupe
version: 1.0.0-beta
api-version: 1.19
author: Prorickey
depend:
  - LuckPerms
commands:
  dupe:
    description: To dupe items. Can dupe up to 6 times
  filter:
    description: To add, remove or list the filter
    permission: admin.filter
  random:
    description: To toggle random items
  spawn:
    description: Teleports you to spawn
  setspawn:
    description: Sets the spawn to the players location
    permission: admin.setspawn
  gamemode:
    aliases:
      - gm
      - gmode
    permission: admin.gamemode
    description: To change the player's own gamemode or others
    usage: /<command> <gamemode> <player>
  gmc:
    aliases:
      - gamemodecreative
    permission: admin.gamemode.creative
    description: To change the player's own gamemode or others to creative mode
    usage: /<command> <player>
  gms:
    aliases:
      - gamemodesurvival
    permission: admin.gamemode.survival
    description: To change the player's own gamemode or others to survival mode
    usage: /<command> <player>
  gmsp:
    aliases:
      - gamemodespectator
    permission: admin.gamemode.spectator
    description: To change the player's own gamemode or others to spectator mode
    usage: /<command> <player>
  gma:
    aliases:
      - gamemodeadventure
    permission: admin.gamemode.adventure
    description: To change the player's own gamemode or others to adventure mode
    usage: /<command> <player>