name: Gradle ShadowJar Build
on: [push, pull_request]
permissions:
  contents: write
  pull-requests: read
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew shadowJar

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Create a Release in a GitHub Action
      uses: comnoco/create-release-action@v2.0.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{github.ref_name}}
        release_name: Release $RELEASE_VERSION
        draft: false
        body: |
          Created automatically by Github Actions
          Commit ${{github.sha}}
        prerelease: false
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: /build/libs/*